### ISSUE TITLE
Broken on OSX, I demand a refund!

### ISSUE THREAD

**Issue by AshyIsMe** [ggVGc/fzf_browser#1]
$ source fzf_browser.sh
-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]

**Comment by ggVGc** [comment]
Should be fixed, for now, by 9b1b9d5

**Comment by AshyIsMe** [comment]
Still not fixed.

``` bash
aaron@Aarons-MacBook-Air:~/CodeBases/fzf_browser * master
$ source fzf_browser.sh

aaron@Aarons-MacBook-Air:~/CodeBases/fzf_browser * master
$ fuzzybrowse
bash: fuzzydir: command not found

aaron@Aarons-MacBook-Air:~/CodeBases/fzf_browser * master
$ fuzzydir
find: illegal option -- m
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
find: illegal option -- m
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]

aaron@Aarons-MacBook-Air:~/CodeBases
$
```

fuzzydir does open fzf but with nothing in the list.

At this point I may have to talk to my legal department and consider suing for damages...

**Comment by ggVGc** [comment]
check it, https://github.com/ggVGc/fzf_browser/commit/328e68d5f7cc87a284c58a99d0529b3b51928447

**Comment by AshyIsMe** [comment]
Ah nice, fuzzydir works now.
fuzzybrowse is still broken though:

``` bash
$ fuzzybrowse
bash: fuzzydir: command not found
```

**Comment by ggVGc** [comment]
fzf_browser.sh needs to be sourced from .bashrc, for now.

**Comment by AshyIsMe** [comment]
Cheers, my lawyers will contact your laywers...
